version: 2.1
orbs:
  # Your orb will be automatically injected here during the pipeline.
  # Reference your orb's jobs and commands below as they will exist when built.
  orb-tools: circleci/orb-tools@12.0
  win: circleci/windows@5.0
  # The orb definition is intentionally not included here. It will be injected into the pipeline.
  unmask: {}

# Use this tag to ensure test jobs always run,
# even though the downstream publish job will only run on release tags.
filters: &filters
  tags:
    only: /.*/

# Filter for release tags.
release-filters: &release-filters
  branches:
    ignore: /.*/
  tags:
    only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

commands:
  test:
    steps:
      - run: echo $MY_ENV_VAR
      - unmask/setup:
          variable: MY_ENV_VAR
      - run: echo $MY_ENV_VAR

jobs:
  # Create jobs to test the commands of your orbs.
  # You may want to add additional validation steps to ensure the commands are working as expected.
  unmask-linux:
    docker:
      - image: cimg/base:current
    resource_class: small
    steps:
      - test
    
  unmask-windows:
    executor: win/default
    shell: bash.exe
    steps:
      - test

  unmask-mac:
    macos:
      xcode: 14.2.0
    steps:
      - test

workflows:
  test-deploy:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      # Test your orb's commands in a custom job and test your orb's jobs directly as a part of this workflow.
      - unmask-linux:
          filters: *filters
      - unmask-windows:
          filters: *filters
      - unmask-mac:
          filters: *filters
      
      - hold-for-review:
          type: approval
          filters: *release-filters
          requires:
            - unmask-linux
            - unmask-windows
            - unmask-mac

      # The orb must be re-packed for publishing, and saved to the workspace.
      - orb-tools/pack:
          filters: *release-filters
      - orb-tools/publish:
          orb_name: aaronstillwell/unmask
          vcs_type: << pipeline.project.type >>
          pub_type: production
          # Ensure this job requires all test jobs and the pack job.
          requires:
            - orb-tools/pack
            - hold-for-review
          context: orb-publishing
          filters: *release-filters
